---
- name: Provision an EC2 Instance
  hosts: localhost
  tasks:
    - name: create ec2 instance
      ec2:
        key_name: Ec2KeyPair
        image: ami-032509850cf9ee54e
        wait: yes
        instance_type: t2.micro
        group_id: sg-0df871cb89d78602d
        vpc_subnet_id: subnet-07c6811d5a119875c
        region: us-west-2
        assign_public_ip: yes
        count: 1
        instance_tags:
          Name: swarm_manager
      register: swarm_manager

    - name: create ec2 instance
      ec2:
        key_name: Ec2KeyPair
        image: ami-032509850cf9ee54e
        wait: yes
        instance_type: t2.micro
        group_id: sg-0df871cb89d78602d
        vpc_subnet_id: subnet-07c6811d5a119875c
        region: us-west-2
        assign_public_ip: yes
        count: 1
        instance_tags:
          Name: swarm_worker
      register: swarm_worker

    - name: Add new instance to launched group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: launched
      with_items:
        - "{{ swarm_manager.instances }}"
        - "{{ swarm_worker.instances }}"

    - name: Add new instance to manager group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: swarm_manager
      with_items:
        - "{{ swarm_manager.instances }}"

    - name: Add new instance to worker group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: swarm_worker
      with_items:
        - "{{ swarm_worker.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 10
        timeout: 20
      with_items:
        - "{{ swarm_manager.instances }}"
        - "{{ swarm_worker.instances }}"

- name: Configure instance
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - docker_machine

- name: Swarm manager init
  hosts: swarm_manager
  become: True
  gather_facts: True
  roles:
    - swarm_manager

- name: Swarm worker join
  hosts: swarm_worker
  become: True
  gather_facts: True
  roles:
    - swarm_worker
