---
- name: Provision an EC2 Instance
  hosts: localhost
  tasks:
    - name: create ec2 instance
      ec2:
        image: ami-032509850cf9ee54e
        wait: yes
        instance_type: t2.micro
        group_id: sg-0df871cb89d78602d
        vpc_subnet_id: subnet-07c6811d5a119875c
        region: us-west-2
        assign_public_ip: no
        count: 2
        instance_tags:
          Name: webserver
        egister: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

- name: Configure instance
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - docker_machine
