---
- name: Provision an EC2 Instance
  hosts: localhost
  tasks:
    - name: create ec2 instance for swarm manager
      ec2:
        key_name: Ec2KeyPair
        image: ami-032509850cf9ee54e
        wait: yes
        instance_type: t2.micro
        group_id: sg-0df871cb89d78602d
        vpc_subnet_id: subnet-07c6811d5a119875c
        region: us-west-2
        assign_public_ip: yes
        count: 1
        instance_tags:
          Name: swarm_manager
        state: present
      register: swarm_manager

    - name: create ec2 instance for swarm workers
      ec2:
        key_name: Ec2KeyPair
        image: ami-032509850cf9ee54e
        wait: yes
        instance_type: t2.micro
        group_id: sg-0df871cb89d78602d
        vpc_subnet_id: subnet-07c6811d5a119875c
        region: us-west-2
        assign_public_ip: yes
        count: 2
        instance_tags:
          Name: swarm_worker
        state: present
      register: swarm_worker

    - name: Add new instance to manager group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: swarm_manager
      with_items:
        - "{{ swarm_manager.instances }}"

    - name: Add new instance to worker group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: swarm_worker
      with_items:
        - "{{ swarm_worker.instances }}"

    - name: Delegate vars
      wait_for_connection:
        delay: 10
        timeout: 20

- name: Configure instance
  hosts: all
  become: True
  gather_facts: True
  roles:
    - docker_machine
    - swarm
