---
# tasks file for docker_machine
- name: Enable amazon-linux-extras epel
  shell: "amazon-linux-extras enable epel"

- name: epel install
  yum:
    name: "{{ item }}"
    state: installed
  loop:
    - epel-release
    - wget

- name: Add the yum repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install Docker
  yum: name={{item}} state=present
  with_items:
    - docker-engine

- name: Start Docker
  service: name=docker state=started

- name: Add user to docker group
  user: name={{ item }} groups=docker append=yes
  with_items: docker_users

- name: Install Docker Compose
  shell: curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }} > /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

- name: Apply executable permissions to docker-compose
  file: path=/usr/local/bin/docker-compose state=file mode=0755

- name: Install bash-completion
  yum: name={{ item }}
  with_items:
    - bash-completion

- name: Install Docker Compose bash_completion
  shell: curl -L https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
  args:
    creates: /etc/bash_completion.d/docker-compose
