---
# tasks file for swarm_manager
- name: Swarm init
  shell: "docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}"

- name: Get token
  shell: "docker swarm join-token -q worker"
  register: worker_token
  delegate_to: "{{ item.private_ip }}"
  delegate_facts: True
  with_items:
    - "{{ swarm_worker.instances }}"
