---
# tasks file for swarm
- name: Swarm init
  shell: "docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}"
  when: "'swarm_manager' in group_names"

- name: Get token
  shell: "docker swarm join-token -q worker"
  register: worker_token
  when: "'swarm_manager' in group_names"

- name: Show Worker Token
  debug: var=hostvars[groups['swarm_manager'][0]]['inventory_hostname']
