---
# tasks file for swarm
- name: Swarm init
  shell: "docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}"
  when: "'swarm_manager' in group_names"

- name: Get token
  shell: "docker swarm join-token -q worker"
  register: worker_token
  delegate_to: "{{ groups['swarm_worker'][0] }}"
  when: "'swarm_manager' in group_names"

- name: Swarm init
  shell: "docker swarm join --token {{ hostvars['swarm_manager']['worker_token']['stdout'] }} {{ hostvars['swarm_manager']['ansible_eth0']['ipv4']['address'] }}:2377"
  when: "'swarm_worker' in group_names"
