---
# tasks file for swarm
- name: Swarm init
  shell: "docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}"
  when: "'swarm_manager' in group_names"

- name: Get token
  shell: "docker swarm join-token -q worker"
  register: worker_token
  when: "'swarm_manager' in group_names"

- name: Show Worker Token
  debug: var=worker_token.stdout

- name: Show Worker Token
  debug: var=hostvars[groups['swarm_manager'][0]]['inventory_hostname']

- name: Swarm init
  shell: "docker swarm join --token {{ hostvars[groups['swarm_manager'][0]]['worker_token']['stdout'] }} {{ hostvars[groups['swarm_manager'][0]]['inventory_hostname'] }}:2377"
  when: "'swarm_worker' in group_names"

- name: Dockerproject
  copy:
    src: docker-compose.yml
    dest: $(pwd)
  when: "'swarm_manager' in group_names"

- name: Docker compose run
  shell: "docker stack deploy --compose-file="$(pwd)/docker-compose.yml" samplewar"
  when: "'swarm_manager' in group_names"
